<?php

namespace AppBundle\Repository;

/**
 * JamJarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JamJarRepository extends \Doctrine\ORM\EntityRepository
{
}
