<?php

namespace AppBundle\Repository;

/**
 * JamTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JamTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
