<?php

namespace AppBundle\Repository;

/**
 * JamYearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JamYearRepository extends \Doctrine\ORM\EntityRepository
{
}
